import {StyleSheet} from 'react-native';
import {COLORS} from '../../utils/colors';

export const styles = StyleSheet.create({
  productDetailsDataLayout: {
    zIndex: 0,
  },
  layout: {
    height: 1000,
    width: 'auto',
  },
  image: {
    width: 250,
    height: 250,
  },
  carouselLeftButton: {
    position: 'absolute',
    right: 25,
    top: 100,
  },
  carouselLeftButtonIcon: {
    color: COLORS.neutral_500,
  },
  carouselRightButton: {
    position: 'absolute',
    left: 25,
    top: 100,
  },
  carouselRightButtonIcon: {
    color: COLORS.neutral_500,
  },
  selectColorButton: {
    display: 'flex',
    flex: 1,
    width: 50,
    height: 30,
    fontSize: 10,
    marginRight: 5,
  },
  buttonGroups: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    bottom: 5,
    marginLeft: 10,
    marginRight: 30,
    marginBottom: 10,
    fontWeight: '700',
    fontSize: 20,
    textAlign: 'justify',
  },
  carouselImage: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 25,
    marginTop: 30,
    marginBottom: 30,
  },
  dotStyle: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginHorizontal: 0,
    backgroundColor: COLORS.neutral_700,
  },
  productName: {
    fontFamily: 'Roboto',
    color: COLORS.neutral_700,
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: '400',
    marginTop: 11,
    marginBottom: 3,
    lineHeight: 20,
  },
  coastBar: {
    bottom: 5,
    marginRight: 17,
  },
  horizontalLine: {
    borderBottomColor: COLORS.neutral_700,
    borderBottomWidth: 2,
    marginBottom: 10,
    width: 'auto',
    marginLeft: 10,
    marginRight: 30,
  },
  description: {
    bottom: 5,
    marginLeft: 10,
    marginRight: 30,
    textAlign: 'justify',
  },
  descriptionSection: {
    bottom: 5,
    marginLeft: 10,
    marginRight: 30,
    marginBottom: 10,
    fontWeight: '700',
    fontSize: 20,
    textAlign: 'justify',
  },
  selectColorSection: {
    bottom: 5,
    marginLeft: 10,
    marginRight: 30,
    marginBottom: 10,
    fontWeight: '700',
    fontSize: 20,
    textAlign: 'justify',
  },
  productSection: {
    bottom: 5,
    marginLeft: 10,
    marginRight: 30,
    fontWeight: '700',
    fontSize: 20,
    textAlign: 'justify',
  },
  price: {
    fontFamily: 'Roboto',
    color: COLORS.neutral_700,
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '700',
    marginTop: 10,
  },
  currency: {
    fontFamily: 'Roboto',
    color: COLORS.neutral_700,
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 20,
  },
  productInfoBar: {
    width: 'auto',
    position: 'absolute',
    top: 300,
    left: 10,
    marginBottom: 20,
  },
  colorSelect: {},
  dotBar: {
    position: 'absolute',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    bottom: -10,
    marginLeft: 10,
    marginRight: 30,
    fontWeight: '700',
  },
  dotNotActive: {
    color: COLORS.accent_red,
  },
  dotActive: {
    color: COLORS.blue_500,
  },
  buttonStyle: {
    backgroundColor: COLORS.neutral_100,
    borderRadius: 0,
    flex: 1,
    height: 30,
    width: 60,
  },
});
