import {StyleSheet} from 'react-native';
import {COLORS} from '../../utils/colors';

export const styles = StyleSheet.create({
  centeredView: {
    flex: 1,
    height: 'auto',
    alignItems: 'center',
  },
  firstBlock: {
    marginTop: 0,
  },
  text: {
    color: COLORS.blue_300,
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: 40,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 50,
  },
  link: {
    color: COLORS.blue_300,
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 50,
    marginTop: 10,
  },
  input: {
    height: 40,
    margin: 12,
    borderWidth: 1,
    padding: 10,
    width: 300,
    borderRadius: 5,
    borderColor: COLORS.neutral_500,
    borderStyle: 'solid',
  },
  inputName: {
    position: 'absolute',
    color: COLORS.neutral_700,
    textAlign: 'left',
    fontFamily: 'Roboto',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 16,
    letterSpacing: 0.4,
    marginLeft: 25,
    top: 4,
    backgroundColor: COLORS.neutral_100,
    zIndex: 1,
  },
  imageView: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.blue_500,
    borderRadius: 100,
    width: 120,
    height: 120,
  },
  imageProfile: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 50,
  },
  modalText: {
    color: COLORS.neutral_500,
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 25,
    marginTop: 40,
  },
  modalDescription: {
    color: COLORS.neutral_500,
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 25,
    marginTop: 10,
  },
  productCard: {
    flex: 1,
    backgroundColor: COLORS.neutral_100,
    marginTop: 30,
    borderRadius: 5,
    marginLeft: 5,
    marginRight: 5,
    height: 150,
    width: 320,
  },
  productCardSum: {
    flex: 1,
    backgroundColor: COLORS.neutral_100,
    marginTop: 30,
    marginLeft: 5,
    marginRight: 5,
    borderRadius: 5,
    height: 165,
    width: 320,
  },
  secureElements: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: 250,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    alignContent: 'center',
    left: 50,
  },
  secureImage: {
    marginRight: 10,
  },
  secureBlock: {

  },
  secureText: {
    color: COLORS.accent_green,
  },
  priceDetails: {
    color: COLORS.neutral_500,
    textAlign: 'left',
    fontFamily: 'Roboto',
    fontSize: 15,
    left: 5,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 25,
    marginBottom: 10,
  },
  priceDetailsItem: {
    color: COLORS.neutral_500,
    textAlign: 'left',
    fontFamily: 'Roboto',
    fontSize: 15,
    left: 5,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
    marginTop: -17,
    width: '50%',
  },
  priceDetailsNumber: {
    color: COLORS.neutral_500,
    textAlign: 'right',
    fontFamily: 'Roboto',
    fontSize: 15,
    left: 5,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
    marginTop: -17,
    width: '50%',
  },
  priceItemsElements: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: 300,
    marginTop: 20,
  },
  splitLine: {
    borderBottomColor: COLORS.neutral_300,
    borderBottomWidth: 1,
    marginLeft: 5,
    marginRight: 5,
    marginTop: 5,
  },
  amount: {
    color: COLORS.neutral_700,
  },
});
