import {StyleSheet} from 'react-native';
import {COLORS} from '../../utils/colors';

export const styles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  centeredViewScroll: {
    flex: 1,
    marginTop: 20,
    alignItems: 'center',
    height: 'auto',
  },
  orderItem: {
    marginBottom: 5,
    width: '30%',
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  orderItemImage: {
    width: 70,
    height: 70,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
  },
  oderItem: {
    color: COLORS.neutral_700,
    textAlign: 'left',
    fontFamily: 'Roboto',
    fontSize: 15,
    left: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
    marginTop: -17,
    width: '70%',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  oderItemTitle: {
    fontFamily: 'Roboto',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '400',
  },
  oderDateItemTitle: {
    fontFamily: 'Roboto',
    fontSize: 12,
    color: COLORS.neutral_500,
    fontStyle: 'normal',
    fontWeight: '400',
  },
  oderDateItem: {
    position: 'absolute',
    fontFamily: 'Roboto',
    fontSize: 12,
    color: COLORS.neutral_500,
    fontStyle: 'normal',
    fontWeight: '400',
    left: 5,
    top: 5,
  },
  orderDetailLink: {
    color: COLORS.blue_500,
    fontFamily: 'Roboto',
    fontSize: 15,
    left: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
    marginTop: 15,
    marginBottom: 10,
  },
  firstBlock: {
    marginTop: 0,
  },
  text: {
    color: COLORS.blue_300,
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: 40,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 50,
  },
  link: {
    color: COLORS.blue_300,
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 50,
    marginTop: 10,
  },
  input: {
    height: 40,
    margin: 12,
    borderWidth: 1,
    padding: 10,
    width: 300,
    borderRadius: 5,
    borderColor: COLORS.neutral_500,
    borderStyle: 'solid',
  },
  inputName: {
    position: 'absolute',
    color: COLORS.neutral_700,
    textAlign: 'left',
    fontFamily: 'Roboto',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 16,
    letterSpacing: 0.4,
    marginLeft: 25,
    top: 4,
    backgroundColor: COLORS.neutral_100,
    zIndex: 1,
  },
  imageView: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.blue_500,
    borderRadius: 100,
    width: 120,
    height: 120,
  },
  imageProfile: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 50,
  },
  modalText: {
    color: COLORS.neutral_500,
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 25,
    marginTop: 40,
  },
  modalDescription: {
    color: COLORS.neutral_500,
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 25,
    marginTop: 10,
  },
  orderData: {
    color: COLORS.neutral_500,
    textAlign: 'left',
    fontFamily: 'Roboto',
    fontSize: 15,
    left: 5,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 25,
    marginBottom: 10,
  },
  priceDetailsNumber: {
    color: COLORS.neutral_500,
    textAlign: 'right',
    fontFamily: 'Roboto',
    fontSize: 15,
    left: 5,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
    marginTop: -17,
    width: '50%',
  },
  priceItemsElements: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: 300,
  },
  splitLine: {
    borderBottomColor: COLORS.neutral_300,
    borderBottomWidth: 1,
    marginLeft: 5,
    marginRight: 5,
    marginTop: 5,
  },
  productInfoBar: {
    display: 'flex',
    position: 'absolute',
    width: 'auto',
  },
  plusButton: {
    width: 30,
    alignItems: 'center',
    borderRadius: 25,
    borderColor: COLORS.neutral_300,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
  },
  orderCard: {
    backgroundColor: COLORS.neutral_100,
    marginTop: 10,
    marginLeft: 5,
    marginRight: 5,
    borderRadius: 5,
    height: 'auto',
    width: 320,
  },
  count: {
    width: 30,
    alignItems: 'center',
    color: COLORS.neutral_300,
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
  },
  minusButton: {
    width: 30,
    alignItems: 'center',
    borderRadius: 20,
    borderColor: COLORS.neutral_300,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
  },
  loadingData: {
    display: 'flex',
    marginLeft: 10,
    fontFamily: 'Roboto',
    fontSize: 15,
    left: 5,
    fontStyle: 'normal',
    fontWeight: '700',
    borderColor: COLORS.neutral_500,
  },
  onLoadDataContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: 600,
    verticalAlign: 'middle',
  },
  onLoadDataHorizontal: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 10,
  },
});
