import {StyleSheet} from 'react-native';
import {COLORS} from '../../utils/colors';

export const styles = StyleSheet.create({
  item: {
    display: 'flex',
    margin: 5,
    flexDirection: 'column',
    alignItems: 'center',
    gap: 5,
    width: 'auto',
    borderRadius: 5,
    backgroundColor: COLORS.neutral_100,
    shadowColor: COLORS.neutral_500,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 2,
    shadowRadius: 4,
    height: 120,
  },
  productDetailsStylesIos: {
    left: 110,
  },
  productDetailsStylesAndroid: {
    left: 120,
  },
  ios: {
    shadowColor: COLORS.neutral_500,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 2,
    shadowRadius: 4,
  },
  android: {
    shadowColor: COLORS.neutral_500,
    shadowRadius: 4,
  },
  image: {
    marginTop: 10,
    marginBottom: 5,
    width: 100,
    height: 100,
    right: 60,
    position: 'absolute',
  },
  productInfoBar: {
    display: 'flex',
    position: 'absolute',
    width: 'auto',
  },
  productName: {
    fontFamily: 'Roboto',
    color: COLORS.neutral_700,
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    marginTop: 11,
    marginLeft: 11,
    lineHeight: 20,
  },
  productDescription: {
    fontFamily: 'Roboto',
    color: COLORS.neutral_700,
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    marginLeft: 11,
    lineHeight: 20,
  },
  coastBar: {
    flexDirection: 'row',
    marginLeft: 11,
    marginRight: 17,
  },
  price: {
    fontFamily: 'Roboto',
    color: COLORS.neutral_700,
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '700',
  },
  currency: {
    fontFamily: 'Roboto',
    color: COLORS.neutral_700,
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 20,
  },
  icon: {
    display: 'flex',
    width: 25,
    height: 25,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    top: 15,
    left: 200,
  },
  delete: {
    width: 25,
    height: 25,
    flexShrink: 0,
    color: COLORS.neutral_700,
  },
});
